---
- hosts: all
  become: true
  become_method: sudo
  remote_user: ubuntu

  tasks:
  - name: Install OpenJDK
    apt:
      name: openjdk-11-jre-headless

  - name: download and extract tomcat packages
    unarchive:
      src: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.71/bin/apache-tomcat-8.5.71.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: Rename apache tomcat version
    command: mv /usr/local/apache-tomcat-8.5.71/ /usr/local/tomcat/
    
  - name: start tomcat services
    shell: nohup /usr/local/tomcat/bin/startup.sh &
